
[aliases]
dcrm = "docker compose down --remove-orphans -v"
dcub = "docker compose up --build"
dcubd = "docker compose up --build -d"
direnv_hook_zsh = "eval \"$(direnv hook zsh)\""
dp = "docker ps"
dpa = "docker ps -a"
drma = "docker rm $(docker ps -aq) -f"
echo1 = "echo 1"
g = "git"
gac = "git add . && git commit -m"
ghnoreply = "echo \"$(gh api user --jq '.id')+$(gh api user --jq '.login')@users.noreply.github.com\""
gitalias = "git config --get-regexp ^alias"
gogit = "cd ~/git"
gr = "./gradlew"
help_screen = "echo 'screen cmd: ctrl + a, then d to detach. screen -r to resume. screen -ls to list.'"
k = "kubectl"
kns = "kubectl config set-context --current --namespace"
ll = "ls -alishF"
prs = "gh pr list --author=\"@me\""
precommit_disable = "export PRE_COMMIT_ALLOW_NO_CONFIG=1"
precommit_enable = "export PRE_COMMIT_ALLOW_NO_CONFIG=0"
print_ssh_config = "cat ~/.ssh/config"
setbashrc = "edit $HOME/.bashrc"
system_docker_disable = "sudo systemctl disable docker.service && sudo systemctl disable containerd.service"
system_docker_start = "sudo systemctl enable docker.service && sudo systemctl enable containerd.service"
tcp_usage = "sudo lsof -nP -iTCP:8080 | grep LISTEN"
windows_sleep = "rundll32.exe powrprof.dll,SetSuspendState 0,1,0"

[exports]
EDITOR = "nvim"

[metadata]
url_origin = "https://github.com/Fabbbou/my-duh"
name_origin = "my-duh"
